paths:
  /linebeacon-api:
    post:
      x-handler: fulfillment
      parameters:
        - in: body
          name: body
          schema:
            type: object
      responses:
        200:
          description: Success
          schema:
            type: object
